### ISSUE TITLE
find error 500

### ISSUE THREAD

**Issue by wangxingdi** [dolfinus/AutoSitemap#10]
what i set:
wfLoadExtension( 'AutoSitemap' );
$wgAutoSitemap["filename"] = "sitemap.xml";
$wgAutoSitemap["server"] = "https://www.developwiki.com";
$wgAutoSitemap["notify"] = [
    'https://www.google.com/webmasters/sitemaps/ping?sitemap=https://www.developwiki.com/sitemap.xml',
    'https://www.bing.com/webmaster/ping.aspx?
sitemap=https://www.developwiki.com/sitemap.xml'
];
but after upload this LocalSettings.php, i find my web is error 500!
i do not know what happen, and how to config in .htaccess ?

**Comment by wangxingdi** [comment]
the AutoSitemap-master was copied in folder extensions already

**Comment by dolfinus** [comment]
Enable [Debug](https://www.mediawiki.org/wiki/Manual:How_to_debug) for your wiki and show trace info. Only 500 error code can't give me enough information.
