### ISSUE TITLE
Not compatible with MW 1.34

### ISSUE THREAD

**Issue by GodMod** [dolfinus/AutoSitemap#13]
When editing an article, the following error message appears:
`MWException from line 164 of <path>/includes/Hooks.php: Invalid callback AutoSitemap::writeSitemap in hooks for RevisionInsertComplete`

**Comment by LitvinTsuba** [comment]
Confirm. For 1.34 i see error message after edit an article:

`UnexpectedValueException from line 462 of /var/www/www-root/data/www/<MY_SITE>/includes/libs/rdbms/loadbalancer/LoadBalancer.php: Invalid server index index #DB_SLAVE`

**Comment by dolfinus** [comment]
Should be fixed now.

**Comment by LitvinTsuba** [comment]
Error in ver 1.4 for MW 1.34 when a try save new page:
`[827fdd1b14a15d2f5179c330] /index.php?title=28_%D0%B4%D0%B5%D0%BA%D0%B0%D0%B1%D1%80%D1%8F&action=submit Wikimedia\Rdbms\DBQueryError from line 1603 of /var/www/www-root/data/www/site.com/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading?
Query: SELECT "Popularpages" AS type,
page_id AS id,
page_namespace AS namespace,
page_title AS title,
(MAX(rev_timestamp)) AS last_modification,
rev_timestamp AS value
FROM
`page`,
`revision`
WHERE
page_is_redirect = 0
AND rev_page = page_id
AND page_namespace NOT IN (1,2,3,5,NS_IMAGE_TALK,8,9,10,11,12,13,15)
GROUP BY page_id
Function: Wikimedia\Rdbms\DBConnRef::query
Error: 1054 Unknown column 'NS_IMAGE_TALK' in 'where clause' (localhost)`

**Comment by dolfinus** [comment]
Try using latest version.
