### ISSUE TITLE
Invalid server index index #DB_SLAVE

### ISSUE THREAD

**Issue by cloudwindy** [dolfinus/AutoSitemap#17]
I'm using latest version, but still got an exception.
`Invalid server index index #DB_SLAVE`

This problem happened when I was saving my edit, so even I have already set `$wgShowExceptionDetails = true;`, no further information was printed out.

MediaWiki Version: 1.34.2
PHP Version: 7.2.33
MySQL Version: 8.0.21

Maybe relevant to #13 .

**Comment by dolfinus** [comment]
Hello.

Try to use latest extension version, I've removed DB_SLAVE usage (deprecated):
https://github.com/dolfinus/AutoSitemap/commit/1acd9cf13609dc6b8609b57d9799e6adaff40888

**Comment by cloudwindy** [comment]
Thank you!
