### ISSUE TITLE
sizeof parameter warning from php 7.3.19

### ISSUE THREAD

**Issue by hexmode** [dolfinus/AutoSitemap#19]
The MediaWiki.org user [Fokebox](https://www.mediawiki.org/wiki/User:Fokebox) reported [problems with this extension](https://www.mediawiki.org/w/index.php?title=Topic:Vtrxldf2a26r6c0q&topic_showPostId=vts1c15xdgkwrlwy#flow-post-vts1c15xdgkwrlwy).

[Visiting his sitemap page](https://wikireshebnik.ru/sitemap_new.xml), I see 

    <b>Warning</b>:  sizeof(): Parameter must be an array or an object that implements Countable in <b>.../sitemap.php</b> on line <b>258</b><br />

**Comment by dolfinus** [comment]
Hello.

Why do you think that exactly this extension is responsible for generating this Warning?
Firstly, there is no `sizeof` function usage in any source file within this repo.
Secondly, this warning is being generated by `/var/www/u0402490/data/www/wikireshebnik.ru/sitemap.php` file. Can you provide it's content?

**Comment by wikijournal** [comment]
The problem is resolved! The problem was that I used old version of the extension generating sitemap, and new one. Now all works fine!
