### ISSUE TITLE
Why the weird default priority?

### ISSUE THREAD

**Issue by TaylanUB** [dolfinus/AutoSitemap#24]
Heya,

First of all thanks for the amazing extension. The `generateSitemap` maintenance script shipped with MediaWiki is kinda lacking IMO so I'm thinking of using this instead even though I have access to `cron`...

Now my question:

It seems that if you don't make any settings related to priority, the extension will set the priority of a page arbitrarily based on its position in the database.

In particular, while looping over all pages, it keeps a `$pos` variable indicating the current loop iteration, and a `$count` variable that's the total number of pages, and each page's priority is set to `$pos / $count` so the priority will slowly go from 0 to 1 while looping over the pages.

Is there any reason for this? It seems like a bad idea to me.

**Comment by dolfinus** [comment]
Hi.

This is some legacy, and can be removed from the extension.
