### ISSUE TITLE
Memory consumption could be reduced

### ISSUE THREAD

**Issue by TaylanUB** [dolfinus/AutoSitemap#25]
In the `writeSitemap` function, the entire contents are built up in a PHP variable as a string, and then written into a file at once. For very large wikis, this could end up consuming lots of memory.

This is made worse by the fact that the function is executed on every single page save (among other events). I'll create a separate issue for that.

A better strategy would be to create a temporary file, write it piece by piece, and move it into the correct file path once done.

**Comment by dolfinus** [comment]
Fix: #28
