### ISSUE TITLE
Rate-limiting the execution of the extension

### ISSUE THREAD

**Issue by TaylanUB** [dolfinus/AutoSitemap#26]
It seems that the extension's main function, `writeSitemap`, is executed every time a page is updated, among some other events. For a highly active wiki, this could cause lots of resource consumption.

There should be a way to rate-limit the execution, and/or offer alternative trigger points for execution.

Ideas:
1. A variable `$wgAutoSitemapRateLimit` or the like which defines after how many events the sitemap should be updated. Not sure how viable this is, because as far as I understand, we would need to save some counter on the filesystem or in the database.
2. A variable `$wgAutoSitemapMinAge` or the like which basically says "if the sitemap exists and isn't older than this, don't update it."

I think the second option would be very easy to implement and offer a good way to rate limit.

**Comment by dolfinus** [comment]
Closed by https://github.com/dolfinus/AutoSitemap/pull/29
