### ISSUE TITLE
Explain Server Setting Better

### ISSUE THREAD

**Issue by LevonBecker** [dolfinus/AutoSitemap#3]
Can you please explain the server setting a little better in the [README.md](https://github.com/dolfinus/AutoSitemap/blob/master/Readme.md)?

```
Setting base url other then $wgServer

Set all sitemap entries get this as their base url? If not set, used $wgCanonicalServer or $wgServer instead:

$wgAutoSitemap["server"] = "https://your-base-url.com";
```

Thanks

**Comment by dolfinus** [comment]
By default, `$wgAutoSitemap["server"]` value is equal `$wgCanonicalServer` value, if it set, or `$wgServer`, if not.
For example, if you have such settings (https correct support):
```php
$wgServer = '//my-site.com';
$wgCanonicalServer='https://my-site.com'
```
the sitemap urls will look like `https://my-site.com/Article'.

$wgCanonicalServer changes wiki`s link policy, so if you doesn`t want to change it, you can set value you need as `$wgAutoSitemap["server"]`.

If you use http only, there is no point to change something, it is already work perfectly.

**Comment by LevonBecker** [comment]
Gotcha thanks
