### ISSUE TITLE
Use of wfGetDB was deprecated in MediaWiki 1.39

### ISSUE THREAD

**Issue by mikerCZ** [dolfinus/AutoSitemap#35]
After upgrading to latest version MediaWiki to 1.42.1 and extension version 1.81.

I see this error in error log

[Wed Sep 25 03:52:45.745647 2024] [proxy_fcgi:error] [pid 2667064:tid 2667127] [remote 89.24.37.106:25714] AH01071: Got error 'PHP message: PHP Deprecated:  Use of wfGetDB was deprecated in MediaWiki 1.39. [Called from AutoSitemap::writeSitemap in /home/mrudolf/domains/wikifood.cz/public_html/extensions/AutoSitemap/AutoSitemap_body.php at line 114] in /home/mrudolf/domains/wikifood.cz/public_html/includes/debug/MWDebug.php on line 379', referer: https://www.wikifood.cz/Speci%C3%A1ln%C3%AD:SmiteSpam
[Wed Sep 25 03:52:46.387633 2024] [proxy_fcgi:error] [pid 2667064:tid 2667132] [remote 89.24.37.106:25714] AH01071: Got error 'PHP message: PHP Deprecated:  Use of wfGetDB was deprecated in MediaWiki 1.39. [Called from AutoSitemap::writeSitemap in /home/mrudolf/domains/wikifood.cz/public_html/extensions/AutoSitemap/AutoSitemap_body.php at line 114] in /home/mrudolf/domains/wikifood.cz/public_html/includes/debug/MWDebug.php on line 379', referer: https://www.wikifood.cz/Speci%C3%A1ln%C3%AD:SmiteSpam
[Wed Sep 25 03:52:47.046249 2024] [proxy_fcgi:error] [pid 2667064:tid 2667131] [remote 89.24.37.106:25714] AH01071: Got error 'PHP message: PHP Deprecated:  Use of wfGetDB was deprecated in MediaWiki 1.39. [Called from AutoSitemap::writeSitemap in /home/mrudolf/domains/wikifood.cz/public_html/extensions/AutoSitemap/AutoSitemap_body.php at line 114] in /home/mrudolf/domains/wikifood.cz/public_html/includes/debug/MWDebug.php on line 379', referer: https://www.wikifood.cz/Speci%C3%A1ln%C3%AD:SmiteSpam

**Comment by dolfinus** [comment]
PRs sre welcome

**Comment by kizule** [comment]
> PRs are welcome

There we go! 😄
