### ISSUE TITLE
Article Limit?

### ISSUE THREAD

**Issue by LevonBecker** [dolfinus/AutoSitemap#5]
The sitemap.xml has 496 articles. I have close to 900 in the namespace I have it narrowed down to.

Think there is a limit somewhere. I know when I use special pages to view a namespace it only shows 500 articles and there are a few hundred more just in that namespace.

No errors showing in the logs even with debug logging.

https://www.bonusbits.com/sitemap.xml

I did find this in **/var/log/php-fpm/7.0/www-error.log**

```[03-Feb-2017 07:09:50 UTC] PHP Warning:  fopen(https://www.google.com/webmasters/sitemaps/ping?sitemap=/sitemap.xml): failed to open stream: HTTP request failed! HTTP/1.0 400 Bad Request
 in /var/www/html/mediawiki/extensions/AutoSitemap/AutoSitemap_body.php on line 231```

Hmm...
http://stackoverflow.com/questions/29945020/failed-to-open-stream-http-request-failed-http-1-0-400-bad-request

Let me look in the **AutoSitemap_body.php**...

huh, no clue... I suck and PHP... So need to get a Ruby replacement :)

Good Luck... I look forward to hearing if there are limits somewhere I need to tweak or not. 

Thanks
-=Levon

**Comment by dolfinus** [comment]
There is no any article count limit in this extension.
For example you can observe example of my site`s [sitemap](https://en.crystalls.info/w/sitemap_en.xml) with about 1400 pages.

Have you tried to set `$wgAutoSitemap["exclude_namespaces"]` to empty array value?

**Comment by dolfinus** [comment]
The error in line 231 says that extension tried to notify Google (or ever search engine your set) that sitemap was changed, but something went wrong. I think it was caused by some parameter in you php settings, which prohibits opening external urls.

**Comment by LevonBecker** [comment]
That makes since on the php setting, I will look into that.

Oh good idea, I'll set exclude blank and see. I have a feeling it's another php setting. Like script memory or something. 

I'll let you know what I find.

**Comment by LevonBecker** [comment]
Yep was fine. The count of pages was throwing me off from special pages. It was counting included every image as well because they technically have a page dedicated. Thanks

But I did find issue with the notify and about to do a pull request with the fix.
